# .github/workflows/update_readme.yml
name: Update Dynamic README

on:
  # Run automatically on a schedule (e.g., every 6 hours)
  schedule:
    - cron: '0 */6 * * *' # Runs at minute 0 past every 6th hour. Adjust as needed.

  # Allow manual triggering from the Actions tab
  workflow_dispatch:

permissions:
  contents: write # Allow the workflow to write to the repository contents

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Use latest version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz # Install the timezone library needed by the script

      - name: Run Update Script
        run: python .github/scripts/update_readme.py # Execute the python script

      # Optional: Add steps for other dynamic content here
      # e.g., Fetching blog posts (see example below)

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Check if README.md was modified
          if ! git diff --quiet README.md; then
            git add README.md
            git commit -m "📝 Update README [skip ci]" -m "Automatically updated timestamp."
            git push
            echo "Changes committed and pushed."
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided automatically